import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const gen  = process.argv[2] === 'generate';

/** Parse @theme-label-en / @theme-label-zh comment headers from CSS files and
 *  write src/themes/generated.ts so the renderer discovers themes automatically. */
function generateThemeMeta() {
	const themeDir = 'src/themes';
	if (!fs.existsSync(themeDir)) return;
	const files = fs.readdirSync(themeDir)
		.filter(f => f.endsWith('.css'))
		.sort();

	const themes = [];
	for (const file of files) {
		const css = fs.readFileSync(path.join(themeDir, file), 'utf8');
		const get = key => {
			const m = css.match(new RegExp(`\\/\\*\\s*@${key}:\\s*(.+?)\\s*\\*\\/`));
			return m ? m[1].trim() : null;
		};
		const labelEn = get('theme-label-en');
		const labelZh = get('theme-label-zh');
		if (!labelEn || !labelZh) continue;
		themes.push({ id: file.replace('.css', ''), labelEn, labelZh });
	}

	const rows = themes
		.map(t => `\t{ id: '${t.id}', labelEn: '${t.labelEn}', labelZh: '${t.labelZh}' },`)
		.join('\n');

	const out = `// Auto-generated by esbuild.config.mjs — do not edit directly.
// To add a theme: create src/themes/<id>.css with @theme-label-en and @theme-label-zh comments.

export interface ThemeMeta {
\tid: string;
\tlabelEn: string;
\tlabelZh: string;
}

export const BUILTIN_THEMES: readonly ThemeMeta[] = [
${rows}
] as const;

export const BUILTIN_THEME_IDS = BUILTIN_THEMES.map(t => t.id);
`;
	fs.writeFileSync(path.join(themeDir, 'generated.ts'), out);
	console.log(`[themes] generated.ts updated (${themes.length} themes: ${themes.map(t => t.id).join(', ')})`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	loader: { '.yaml': 'text' },
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

/** Append all src/themes/*.css into styles.css after each build.
 *  Truncates any previously appended themes section first so repeated builds
 *  don't accumulate stale CSS rules that can't be overridden. */
function appendThemeCSS() {
	const themeDir = 'src/themes';
	if (!fs.existsSync(themeDir)) return;
	const files = fs.readdirSync(themeDir).filter(f => f.endsWith('.css')).sort();
	if (files.length === 0) return;
	const separator = '\n\n/* ── Built-in themes (auto-generated — do not edit below) ──── */\n';
	// Strip any previously appended themes block before re-appending.
	let base = fs.readFileSync('styles.css', 'utf8');
	const cutIdx = base.indexOf(separator);
	if (cutIdx !== -1) base = base.slice(0, cutIdx);
	const css = base + separator + files.map(f => fs.readFileSync(path.join(themeDir, f), 'utf8')).join('\n');
	fs.writeFileSync('styles.css', css);
}

if (gen) {
	generateThemeMeta();
	process.exit(0);
} else if (prod) {
	generateThemeMeta();
	await context.rebuild();
	appendThemeCSS();
	process.exit(0);
} else {
	generateThemeMeta();
	appendThemeCSS();
	await context.watch();
}
